#!/bin/bash
logs_dir=/data/logs

# Prepare environment
mkdir -p $logs_dir /data/hbase /data/run

#start hbase
/opt/hbase/bin/start-hbase.sh 2>&1

#start omid
/opt/omid/bin/omid.sh create-hbase-commit-table 2>&1
/opt/omid/bin/omid.sh create-hbase-timestamp-table 2>&1
JVM_FLAGS=-Xmx3221225472 /opt/omid/bin/omid.sh tso 2>&1  &

#start phoenix
/opt/phoenix/bin/queryserver.py 2>&1 &
phoenix_pid="$!"

echo Phoenix running with PID ${phoenix_pid}.
wait ${phoenix_pid}
