#!/bin/bash

# Copyright 2021 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

logs_dir=/data/logs

# Prepare environment
mkdir -p $logs_dir /data/hbase /data/run

# Start Apache HBase
/opt/hbase/bin/start-hbase.sh 2>&1

# Start Apache Omid
/opt/omid/bin/omid.sh create-hbase-commit-table 2>&1
/opt/omid/bin/omid.sh create-hbase-timestamp-table 2>&1
JVM_FLAGS=-Xmx3221225472 /opt/omid/bin/omid.sh tso 2>&1  &

# Start Apache Phoenix Query Server
/opt/phoenix/bin/queryserver.py 2>&1 &
phoenix_pid="$!"

echo Phoenix running with PID ${phoenix_pid}.
wait ${phoenix_pid}
